# Generated by Django 4.1.7 on 2023-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_scrapp_alter_orderr_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_scrapp',
            name='name',
            field=models.CharField(max_length=600),
        ),
    ]
