# Generated by Django 4.1.7 on 2023-05-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_scrapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product_Scrapp',
        ),
    ]
